acxz/pkgbuilds

python-databricks-cli/.SRCINFO, python-databricks-cli/PKGBUILD
The AUR package python-libconfigparser was renamed to python-configparser in PRQ#18283
(https://lists.archlinux.org/pipermail/aur-requests/2020-March/038387.html). For Python 3.8 currently used in Arch Linux this package should not be necessary at all since it is a backport of the module that Python offers natively since version 3.6.
=> upgpkg: python-databricks-cli 0.9.1-2: remove python-libconfigparser

archimedes-tools/.SRCINFO, archimedes-tools/PKGBUILD, archimedes-tools/triangle_definitions.patch
I have revisited the versions of triangle and its inclusion in PETSc.
The version provided by PETSc is outdated. The vanilla version works, but requires the following changes to the header. Otherwise, REAL and VOID are not defined.
=> [triangle] Fix triangle.h

python-dm-tree-git/.SRCINFO, python-dm-tree-git/PKGBUILD, python-dm-tree/.SRCINFO, python-dm-tree/PKGBUILD
Update `makedepends` of python-dm-tree and its git alternative: [bazel](https://www.archlinux.org/packages/community/x86_64/bazel/).
Resolve #44
=> [Fix #44] update makedepends of python-dm-tree and its git alternative

orocos-kdl-python-git/.SRCINFO, orocos-kdl-python-git/PKGBUILD
When python2 is installed, cmake will prefer the python2 interpreter over the python3 interpreter.
This ultimately leads to a build error because `sipconfig.py` is not found (because only python-sip is a dependency but not python2-sip).
Adding a line fixes this by always using Python 3 to build.
=> [orocos-kdl-python-git] use the right python interpreter

vgrep/.SRCINFO, vgrep/PKGBUILD
The current version of the package makes everything in `src/pkg/mod/*/*` read only, even for the owner, resulting in an unnecessary, if simple to resolve, hurdle when removing them (for example, for `--cleanbuild`).  Additionally, successive rebuilds are not possible due to a missing `-p` flag in the first execution of `mkdir`.
In order to fix the first problem I resorted to the Arch [Go package guidelines](https://wiki.archlinux.org/index.php/Go_package_guidelines), because I'm not familiar with building Go programs.  This made me notice a few aspects of the package that could be brought up to the current standard and, arguably though I agree with the guidelines), simplified.
Go-specific changes:
- do not create `bin` / `pkg` / `src` directories
- ensure the build system flags are used, …
=> [vgrep] fix small hurdles and modernize according to current guidelines

python-cfclient/.SRCINFO, python-cfclient/PKGBUILD
according to the comments in https://aur.archlinux.org/packages/crazyflie-udev
=> [python-cfclient] add udev rules as opt. dependencies

directfb/.SRCINFO, directfb/PKGBUILD
resolves #25 
I have added a `flux-git` package to AUR [here](https://aur.archlinux.org/packages/flux-git/). This provides `fluxcomp` and adding that to `makedepends` of this package solves https://github.com/acxz/pkgbuilds/issues/25 for me.
=> Add fluxcomp as a directfb makedepend

python-vispy/.SRCINFO, python-vispy/PKGBUILD
I was trying to install python-vispy and this crashed with
```
/var/tmp/pamac-build/python-vispy/src/vispy-0.6.6/.eggs/setuptools_scm-4.1.2-py3.8.egg/setuptools_scm/version.py:202: UserWarning: meta invoked without explicit configuration, will use defaults where required.
warnings.warn(
`npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
rebuilding js and css failed
missing files: ['/var/tmp/pamac-build/python-vispy/src/vispy-0.6.6/vispy/static/extension.js', '/var/tmp/pamac-build/python-vispy/src/vispy-0.6.6/vispy/static/index.js']
Traceback (most recent call last):
File "setup.py", line 179, in <module>
setup(
File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
return distutils.core.setup(**attrs)
File …
```
=> Add missing dependency on npm

half/.SRCINFO, half/PKGBUILD, half/f16c_fix.patch
Bug:
The immintrin.h header will not be included if ```HALF_ENABLE_F16C_INTRINSICS``` wasn't provided manually.
```HALF_ENABLE_F16C_INTRINSICS``` though will be set to ```__F16C__``` which compilers (GCC) provide if a proper ```-march``` flag is given, so this enables the intrinsics without having included the header above.
Compiler errors ensue because things like ```_mm_set_ss``` are not declared.
PR fixes this by putting the include directive after ```HALF_ENABLE_F16C_INTRINSICS``` being set to ```__F16C__``` which the compiler should set.
Issue mailed to upstream, bug is known but no bugfix release out yet.
Keep a look out for next release where this will hopefully be fixed.
Patches #94
=> [half] Fix a bug in the half.hpp include file not enabling F16C intrinsics correctly when the architecture supports it.

ogre-1.9/.SRCINFO, ogre-1.9/PKGBUILD
I noticed that new boost 1.75 broke Gazebo. Gazebo depends on `ogre-1.9` which in turn seems to depend on `libboost_thread.so.1.75.0`, even I could not find it on ogre build instructions:
```
$ readelf -d elfbin /usr/lib/libOgre* | grep boost
readelf: Error: 'elfbin': No such file
0x0000000000000001 (NEEDED)             Shared library: [libboost_thread.so.1.75.0]
0x0000000000000001 (NEEDED)             Shared library: [libboost_thread.so.1.75.0]
0x0000000000000001 (NEEDED)             Shared library: [libboost_thread.so.1.75.0]
0x0000000000000001 (NEEDED)             Shared library: [libboost_thread.so.1.75.0]
0x0000000000000001 (NEEDED)             Shared library: [libboost_thread.so.1.75.0]
0x0000000000000001 (NEEDED)             Shared library: [libboost_thread.so.1.75.0]
```
I added …
=> ogre-1.9 needs boost-libs

sdformat/.SRCINFO, sdformat/PKGBUILD
Since version 10.0.0 tinyxml has been replaced by tinyxml2.
See the [changelog](https://github.com/osrf/sdformat/blob/master/Changelog.md#libsdformat-1000-2020-09-28).
=> Replace tinyxml dependency with tinyxml2

yolo-mark-git/PKGBUILD
Remove `conflicts` clause since this package does not conflict.
=> Fix: ERROR: conflicts is not allowed to be empty.

cegui/.SRCINFO, cegui/PKGBUILD
Closes #133 
Added support for c++11 definitions. Fixes build error on cegui 0.8.7.
=> Add support for c++11 std to fix build error.

ogre-1.9/.SRCINFO, ogre-1.9/PKGBUILD
Just adding 'ogre' wouldn't work, as it would leave out versions >=2.0
=> Add 'ogre[-docs]>=1.0' to the package conflicts

vgrep/.SRCINFO, vgrep/PKGBUILD
=> go is a build-time dependency only for vgrep, moving go to makedepends

qgroundcontrol/PKGBUILD
Git's `protocol.file.allow` is changed to be "user" by default from git v2.38.1, see https://lore.kernel.org/lkml/xmqq4jw1uku5.fsf@gitster.g/
which results in `fatal: transport 'file' not allowed` when initializing submodules. The added `-c protocol.file.allow=always` option fixes this.
=> [QGroundControl] Fix for git's behavioral change.

rapidxml/PKGBUILD
Updates source URL for RapidXML PKGBUILD as according to [this comment](https://aur.archlinux.org/packages/rapidxml#comment-857991).
This change is required because the unauthenticated git protocol on port 9418 is no longer supported, so the current build fails without this fix.
=> Fix RapidXml source URL

python-hydra-core/.SRCINFO, python-hydra-core/PKGBUILD, python-hydra-core/antlr4-jar.patch
Maybe, some auxiliary constrains on java runtime are needed in advance.
https://aur.archlinux.org/packages/python-hydra-core
=> [python-hydra-core] Fix antlr4 runtime version

matplotplusplus/.SRCINFO, matplotplusplus/PKGBUILD
With this upgrade, fixes gcc-13 compatibility. Today, the package can not build with the old version.
=> [matplotplusplus] Update to 1.2.0

rapidxml/.SRCINFO, rapidxml/PKGBUILD
Hello, I have come across rapidxml as a dependency of other pkgbuilds, I build them all in clean chroot, rapidxml initially failed because of missing git as makedepends so I take a look
* pkgname don't have to be in pkgdesc
* please use upstream url
* please use upstream source archive
* removed not needed provides=("rapidxml")
* use sha256 or higher for cheksum
* some style changes, if you don't like let me know
=> [rapidxml] revision

octomap/.SRCINFO, octomap/PKGBUILD, orocos-kdl-python/.SRCINFO, orocos-kdl-python/PKGBUILD
`PyKDL` is used by `tf2-sensor-msgs`. `dist-packages` is not included in the `sys.path` by default. It is recommended to use `site-packages` instead. `site-packages` is used when building this package with ROS activated.
=> install PyKDL to site-packages instead and update octomap to 1.10.0
